-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2022-12-13 14:46:06 BDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE groupinfo CASCADE CONSTRAINTS;

DROP TABLE match CASCADE CONSTRAINTS;

DROP TABLE player CASCADE CONSTRAINTS;

DROP TABLE schedule CASCADE CONSTRAINTS;

DROP TABLE team CASCADE CONSTRAINTS;

CREATE TABLE groupinfo (
    groupid     NUMBER(1) NOT NULL,
    groupname   VARCHAR2(1) NOT NULL
);

ALTER TABLE groupinfo ADD CONSTRAINT groupinfo_pk PRIMARY KEY ( groupid );

CREATE TABLE match (
    matchid       NUMBER(2) NOT NULL,
    stage         VARCHAR2(10) NOT NULL,
    away_teamid   NUMBER(2) NOT NULL,
    home_teamid   NUMBER(2) NOT NULL,
    scheduleid    VARCHAR2(3) NOT NULL
);

CREATE UNIQUE INDEX match__idx ON
    match ( scheduleid ASC );

ALTER TABLE match ADD CONSTRAINT match_pk PRIMARY KEY ( matchid );

CREATE TABLE player (
    playerid             NUMBER(5) NOT NULL,
    playername           VARCHAR2(20) NOT NULL,
    playerjerseynumber   NUMBER(2),
    playerposition       VARCHAR2(10) NOT NULL,
    teamid               NUMBER(2) NOT NULL
);

ALTER TABLE player ADD CONSTRAINT player_pk PRIMARY KEY ( playerid );

CREATE TABLE schedule (
    scheduleid   VARCHAR2(3) NOT NULL,
    matchdate    DATE NOT NULL,
    matchtime    VARCHAR2(10) NOT NULL,
    stadium      VARCHAR2(10)
);

ALTER TABLE schedule ADD CONSTRAINT schedule_pk PRIMARY KEY ( scheduleid );

CREATE TABLE team (
    teamid        NUMBER(2) NOT NULL,
    teamname      VARCHAR2(15),
    teammanager   VARCHAR2(15),
    region        VARCHAR2(10) NOT NULL,
    groupid       NUMBER(1) NOT NULL
);

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( teamid );

ALTER TABLE match
    ADD CONSTRAINT match_schedule_fk FOREIGN KEY ( scheduleid )
        REFERENCES schedule ( scheduleid );

ALTER TABLE match
    ADD CONSTRAINT match_team_fk FOREIGN KEY ( home_teamid )
        REFERENCES team ( teamid );

ALTER TABLE match
    ADD CONSTRAINT match_team_fkv2 FOREIGN KEY ( away_teamid )
        REFERENCES team ( teamid );

ALTER TABLE player
    ADD CONSTRAINT player_team_fk FOREIGN KEY ( teamid )
        REFERENCES team ( teamid );

ALTER TABLE team
    ADD CONSTRAINT team_groupinfo_fk FOREIGN KEY ( groupid )
        REFERENCES groupinfo ( groupid );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             1
-- ALTER TABLE                             10
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
